---
title: "Evaluation of p-curve simulation results"
author: "Felix Schönbrodt & Angelika Stefan"
date: today
execute:
  cache: true
format: 
  html:
    code-fold: true
---


```{r}
#| include: false

# ==============================================================================
# Eval scenarios
# ==============================================================================

library(fitPCurve)
library(rio)
library(dplyr)
library(ggplot2)

# The working directory should be the project root
# if quarto:render is called
if (!interactive()) {
  print("Switching working directory to project root")
  setwd("..")
}

# reference p-curves
pcurves <- import("simulations/reference-pcurves.csv")

# load the multiple DV simulation results:
simres_realistic <- import("simulations/sim-results/sim_realistic.csv")
simres_worst <- import("simulations/sim-results/sim_worst.csv")
simres_perfect <- import("simulations/sim-results/sim_perfect.csv")
simres_H0 <- import("simulations/sim-results/sim_H0.csv")

# load the optional stopping simulation results:
simres_optStop_worst <- import("simulations/sim-results/sim_optStop_worst.csv")
simres_optStop_realistic <- import("simulations/sim-results/sim_optStop_realistic.csv")

simres_multDV <- rbind(simres_realistic, simres_worst, simres_perfect, simres_H0)
simres_multDV$binsum <- rowSums(simres_multDV[, paste0("p", 1:5)])
stopifnot(all(simres_multDV$binsum |> round(6) == 1))
simres_multDV$type <- "multDV"



simres_optStop <- rbind(simres_optStop_realistic, simres_optStop_worst)
simres_optStop$binsum <- rowSums(simres_optStop[, paste0("p", 1:5)])
stopifnot(all(simres_optStop$binsum |> round(6) == 1))
simres_optStop$type <- "optStop"

# combine simulations from both p-hacking strategies (they have different parameter columns)
simres <- bind_rows(simres_multDV, simres_optStop)

simres_multDV$rmseSotola    <- apply(simres_multDV[, paste0("p", 1:5)], 1, function(x) rmse(x, simplify2array(pcurves[1, paste0("p", 1:5)])))
simres_multDV$rmseWetzels   <- apply(simres_multDV[, paste0("p", 1:5)], 1, function(x) rmse(x, simplify2array(pcurves[2, paste0("p", 1:5)])))
simres_multDV$rmseSimonsohn <- apply(simres_multDV[, paste0("p", 1:5)], 1, function(x) rmse(x, simplify2array(pcurves[3, paste0("p", 1:5)])))
simres_optStop$rmseSotola    <- apply(simres_optStop[, paste0("p", 1:5)], 1, function(x) rmse(x, simplify2array(pcurves[1, paste0("p", 1:5)])))
simres_optStop$rmseWetzels   <- apply(simres_optStop[, paste0("p", 1:5)], 1, function(x) rmse(x, simplify2array(pcurves[2, paste0("p", 1:5)])))
simres_optStop$rmseSimonsohn <- apply(simres_optStop[, paste0("p", 1:5)], 1, function(x) rmse(x, simplify2array(pcurves[3, paste0("p", 1:5)])))

simres_multDV$chi2Sotola    <- apply(simres_multDV[, paste0("p", 1:5)], 1, function(x)
    chi2(x, simplify2array(pcurves[1, paste0("p", 1:5)]), n = pcurves$nsig[1])
  )
simres_multDV$chi2Wetzels   <- apply(simres_multDV[, paste0("p", 1:5)], 1, function(x)
    chi2(x, simplify2array(pcurves[2, paste0("p", 1:5)]), n = pcurves$nsig[2])
  )
simres_multDV$chi2Simonsohn <- apply(simres_multDV[, paste0("p", 1:5)], 1, function(x)
    chi2(x, simplify2array(pcurves[3, paste0("p", 1:5)]), n = pcurves$nsig[3])
  )

simres_optStop$chi2Sotola    <- apply(simres_optStop[, paste0("p", 1:5)], 1, function(x)
    chi2(x, simplify2array(pcurves[1, paste0("p", 1:5)]), n = pcurves$nsig[1])
  )
simres_optStop$chi2Wetzels   <- apply(simres_optStop[, paste0("p", 1:5)], 1, function(x)
    chi2(x, simplify2array(pcurves[2, paste0("p", 1:5)]), n = pcurves$nsig[2])
  )
simres_optStop$chi2Simonsohn <- apply(simres_optStop[, paste0("p", 1:5)], 1, function(x)
    chi2(x, simplify2array(pcurves[3, paste0("p", 1:5)]), n = pcurves$nsig[3])
  )







# # A heatmap with all conditions (no averaging; each condition is one tile)
# ggplot(simres, aes(x = d, y = prop_H1, fill = rmseSimonsohn)) +
#   geom_tile() +
#   facet_grid(
#     rows = vars(het, nvar, strategy),      # two stacked facet rows
#     cols = vars(r, prop_Hacker)  # two stacked facet columns
#   ) +
#   scale_fill_viridis_c(
#     option = "inferno",
#     direction = -1,
#     values = c(0, 0.1, 1),
#     limits=c(
#       min(simres |> select(contains("rmse"))),
#       max(simres |> select(contains("rmse")))
#     )
#   ) +
#   scale_y_continuous(breaks = sort(unique(simres$r))) +
#   theme_minimal(base_size = 9) +
#   theme(
#     panel.spacing.x = unit(0.01, "lines"),
#     panel.spacing.y = unit(0.01, "lines")
#   )



#--------------------------------------------------------------------------------
# Some sanity checks

# Correlation between our two GOF measures (rmse and chi2)
cor(simres_multDV$rmseSotola, simres_multDV$chi2Sotola)
cor(simres_multDV$rmseWetzels, simres_multDV$chi2Wetzels)
cor(simres_multDV$rmseSimonsohn, simres_multDV$chi2Simonsohn)

cor(simres_optStop$rmseSotola, simres_optStop$chi2Sotola)
cor(simres_optStop$rmseWetzels, simres_optStop$chi2Wetzels)
cor(simres_optStop$rmseSimonsohn, simres_optStop$chi2Simonsohn)

```


# Some synthetic p-curves: Testing specific scenarios

## Test a pure bump

### Multiple DVs
```{r}
#| echo: false

# all multDV scenarios:
simres_multDV$rmseBump <- apply(simres_multDV[, paste0("p", 1:5)], 1, function(x) rmse(x, c(.15, .15, .15, .15, 4.0)))
plot_pcurves(simres_multDV, poriginal = c(.15, .15, .15, .15, .40), n_best = 10) + ggtitle("Multiple DVs")
```

The best fitting scenarios from the "multiple DVs" simulations are:
```{r}
simres_multDV |> arrange(rmseBump) |> slice(1:5) |> select(1:14) |> round(2) |> print()
```

### Optional Stopping
```{r}
# all optStop scenarios:
simres_optStop$rmseBump <- apply(simres_optStop[, paste0("p", 1:5)], 1, function(x) rmse(x, c(.15, .15, .15, .15, 4.0)))
plot_pcurves(simres_optStop, poriginal = c(.15, .15, .15, .15, .40), n_best = 10) + ggtitle("Optional Stopping")
```

The best fitting scenarios from the "optional stopping" simulations are:
```{r}
simres_optStop |> arrange(rmseBump) |> slice(1:5) |> select(1:12) |> round(2) |> print()
```

```{r}

## Test a "true signal + bump" pattern with a custom p-curve

reference <- c(.40, .20, .10, .05, .25)
reference <- c(.45, .22, .14, .05, .14)

# all multDV scenarios:
simres_multDV$rmseBump2 <- apply(simres_multDV[, paste0("p", 1:5)], 1, function(x) rmse(x, reference))
plot_pcurves(simres_multDV, poriginal = reference, n_best = 10, GOF="rmse")
```

```{r}
simres_multDV |> arrange(rmseBump2) |> slice(1:5)
```

```{r}

# all optStop scenarios:
simres_optStop$rmseBump2 <- apply(simres_optStop[, paste0("p", 1:5)], 1, function(x) rmse(x, reference))
plot_pcurves(simres_optStop, poriginal = reference, n_best = 10, GOF="rmse")
```

```{r}
simres_optStop |> arrange(rmseBump2) |> slice(1:5)
```





```{r}
simres_multDV[order(simres_multDV$chi2Sotola)[1:10], ]
simres_multDV[order(simres_multDV$chi2Wetzels)[1:10], ]
simres_multDV[order(simres_multDV$chi2Simonsohn)[1:10], ]

plot_pcurves(simdat = simres_multDV, poriginal = pcurves[pcurves$dataset == "sotola", paste0("p", 1:5)], n_best=10, GOF="chi2", n = pcurves$nsig[1])
plot_pcurves(simdat = simres_multDV, poriginal = pcurves[pcurves$dataset == "wetzels", paste0("p", 1:5)], n_best=10, GOF="chi2", n = pcurves$nsig[2])
plot_pcurves(simdat = simres_multDV, poriginal = pcurves[pcurves$dataset == "simonsohn", paste0("p", 1:5)], n_best=10, GOF="chi2", n = pcurves$nsig[3])

plot_pcurves(simdat = simres_optStop, poriginal = pcurves[pcurves$dataset == "sotola", paste0("p", 1:5)], n_best=10, GOF="chi2", n = pcurves$nsig[1])
plot_pcurves(simdat = simres_optStop, poriginal = pcurves[pcurves$dataset == "wetzels", paste0("p", 1:5)], n_best=10, GOF="chi2", n = pcurves$nsig[2])
plot_pcurves(simdat = simres_optStop, poriginal = pcurves[pcurves$dataset == "simonsohn", paste0("p", 1:5)], n_best=10, GOF="chi2", n = pcurves$nsig[3])

```