#' Generate a Sharded Cache Filename for a Single Condition
#'
#' @description
#' Computes a stable hash for a single-row data frame representing a condition,
#' and constructs a two-level directory shard under a specified base directory
#' to avoid placing too many files in one folder. Returns the full path
#' (including “.rds” extension) where the result for that condition should be stored.
#'
#' @param cond_row A one‐row [data.frame] whose contents will be hashed. All columns
#'   of the row are serialized to influence the hash value.
#' @param base_dir A single string giving the base directory in which to create
#'   the two‐level shard hierarchy.
#' @param algo A single string naming the hashing algorithm to use (passed
#'   to [digest::digest]). Defaults to `"xxhash64"`.
#'
#' @details
#' 1. **Stable hash**: The row is serialized in full so that changes in any
#'    column yield a different hash.
#' 2. **Two‐level sharding**: The first four hex characters of the hash
#'    (00–ff) are split into two pairs, creating subdirectories
#'    `base_dir/shard1/shard2`.
#' 3. **Directory creation**: If the target shard directory does not exist,
#'    it is created (with `recursive = TRUE`).
#' 4. **Filename**: The full filename is `hash_val.rds`, placed in the
#'    shard directory.
#'
#' @return
#' A single string with the full file path (including the `.rds` extension)
#' where the cached result for the given condition should be written or read.
#'
#' @importFrom digest digest
#' @export
get_cache_filename <- function(cond_row, base_dir, algo = "xxhash64") {
  stopifnot(is.data.frame(cond_row), nrow(cond_row) == 1)

  # 1. Stable hash of the row -----------------------------------------------
  # Serialize the row so that *all* columns influence the hash
  hash_val <- digest::digest(cond_row, algo = algo)

  # 2. Two-level shard (00–ff / 00–ff) --------------------------------------
  shard1 <- substr(hash_val, 1, 2)
  shard2 <- substr(hash_val, 3, 4)
  dir_path  <- file.path(base_dir, shard1, shard2)

  if (!dir.exists(dir_path))
    dir.create(dir_path, recursive = TRUE, showWarnings=FALSE)

  # 3. Write the result ------------------------------------------------------
  file_path <- file.path(dir_path, paste0(hash_val, ".rds"))
  return(file_path)
}



#' Save an R Object to a Sharded Cache File
#'
#' @description
#' Wrapper around [base::saveRDS] that writes an R object to a specified file
#' path, using a chosen compression algorithm. Intended for use with
#' cache filenames generated by [get_cache_filename()].
#'
#' @param object The R object to be serialized and saved.
#' @param file A string specifying the file path (including filename and
#'   extension) where the object will be stored. Typically an `.rds` file.
#' @param compress A single string indicating the compression algorithm to
#'   use. Passed to the `compress` argument of [saveRDS()]. Common options
#'   include `"none"`, `"gzip"`, `"bzip2"`, and `"xz"`. Defaults to `"xz"`.
#' @export
save_cached_file <- function(object, file, compress = "xz") {
  saveRDS(object, file, compress = compress)
}

#' Compute cumulative variance
#' @description Iteratively compute variance of 1:k, 1:k+1, 1:k+2 datapoints in a vector
#' @param x Vector containing values for variance computation
#' @export

cumvar <- function (x) {
  x <- x - x[sample.int(length(x), 1)]  ## see Remark 2 below
  n <- seq_along(x)
  (cumsum(x ^ 2) - cumsum(x) ^ 2 / n) / (n - 1)
}
